### ISSUE TITLE
[Crash] What is wrong?

### ISSUE THREAD

**Issue by Nokius** [andrexus/terraform-provider-proxmox#2]
Hi andrexus,

I like your project a lot, I just updated my proxmox homelab to 5.1 after a long time using a older version.

As it's time to move on I want to code my home infrastructure and atm one of the common tools it terraform, so I discovered your great project.

After looking into the code I created this main.tf for testing
~~~~
provider "proxmox" {
  host = "goofy" # one of my local nodes
}

resource "proxmox_resource_vm" "test" {
  vm_id = "102" # this is required so I used the next free id on my node 
  node = "goofy"
  name = "test"
  memory = "512"
  cores = "1"
}
~~~~  

this is a simple test VM
`terraform init ` works well 

when running `terraform plan`

I get asked for the password and user and it blows up 

~~~~
$ terraform plan
provider.proxmox.password
  Password for API operations.

  Enter a value: my_secret_pw

provider.proxmox.username
  Username for API operations.

  Enter a value: fancyvmmaster

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

Error: Error running plan: 1 error(s) occurred:

* provider.proxmox: unexpected EOF


panic: Post goofy/api2/json/access/ticket: unsupported protocol scheme ""
2018-01-23T22:37:15.185+0100 [DEBUG] plugin.terraform-provider-proxmox: 
2018-01-23T22:37:15.185+0100 [DEBUG] plugin.terraform-provider-proxmox: goroutine 53 [running]:
2018-01-23T22:37:15.185+0100 [DEBUG] plugin.terraform-provider-proxmox: github.com/andrexus/terraform-provider-proxmox/vendor/github.com/andrexus/goproxmox.NewClient(0xc420375d80, 0x5, 0xc420375da0, 0x6, 0xc420375d90, 0x7, 0xc4203d33b0)
2018-01-23T22:37:15.185+0100 [DEBUG] plugin.terraform-provider-proxmox: 	/home/travis/gopath/src/github.com/andrexus/terraform-provider-proxmox/vendor/github.com/andrexus/goproxmox/goproxmox.go:88 +0x58b
2018-01-23T22:37:15.185+0100 [DEBUG] plugin.terraform-provider-proxmox: github.com/andrexus/terraform-provider-proxmox/proxmox.(*Config).Client(0xc42039da60, 0xc6ac51, 0x8, 0xb233a0)
2018-01-23T22:37:15.185+0100 [DEBUG] plugin.terraform-provider-proxmox: 	/home/travis/gopath/src/github.com/andrexus/terraform-provider-proxmox/proxmox/config.go:17 +0x56
2018-01-23T22:37:15.185+0100 [DEBUG] plugin.terraform-provider-proxmox: github.com/andrexus/terraform-provider-proxmox/proxmox.providerConfigure(0xc4203d33b0, 0xc4203d33b0, 0xc4203d69f0, 0xc4202ed820, 0x0)
2018-01-23T22:37:15.185+0100 [DEBUG] plugin.terraform-provider-proxmox: 	/home/travis/gopath/src/github.com/andrexus/terraform-provider-proxmox/proxmox/provider.go:54 +0x1ef
2018-01-23T22:37:15.185+0100 [DEBUG] plugin.terraform-provider-proxmox: github.com/andrexus/terraform-provider-proxmox/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Configure(0xc420312bd0, 0xc4203d69f0, 0xc4202ed7e0, 0xc4202ed800)
2018-01-23T22:37:15.185+0100 [DEBUG] plugin.terraform-provider-proxmox: 	/home/travis/gopath/src/github.com/andrexus/terraform-provider-proxmox/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:240 +0xca
2018-01-23T22:37:15.185+0100 [DEBUG] plugin.terraform-provider-proxmox: github.com/andrexus/terraform-provider-proxmox/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Configure(0xc420294ea0, 0xc4203d69f0, 0xc4203826e0, 0x0, 0x0)
2018-01-23T22:37:15.185+0100 [DEBUG] plugin.terraform-provider-proxmox: 	/home/travis/gopath/src/github.com/andrexus/terraform-provider-proxmox/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:478 +0x3e
2018-01-23T22:37:15.185+0100 [DEBUG] plugin.terraform-provider-proxmox: reflect.Value.call(0xc42029e720, 0xc420382530, 0x13, 0xc6655f, 0x4, 0xc42037af20, 0x3, 0x3, 0x20002, 0xc4202b471c, ...)
2018-01-23T22:37:15.185+0100 [DEBUG] plugin.terraform-provider-proxmox: 	/home/travis/.gimme/versions/go/src/reflect/value.go:440 +0x8f2
2018-01-23T22:37:15.185+0100 [DEBUG] plugin.terraform-provider-proxmox: reflect.Value.Call(0xc42029e720, 0xc420382530, 0x13, 0xc4202b4720, 0x3, 0x3, 0x7c442b, 0x1, 0x0)
2018-01-23T22:37:15.185+0100 [DEBUG] plugin.terraform-provider-proxmox: 	/home/travis/.gimme/versions/go/src/reflect/value.go:308 +0xa4
2018-01-23T22:37:15.185+0100 [DEBUG] plugin.terraform-provider-proxmox: net/rpc.(*service).call(0xc4202eaac0, 0xc420381130, 0xc420375c10, 0xc420388800, 0xc4202ed300, 0xbfb0e0, 0xc4203d69f0, 0x16, 0xafdac0, 0xc4203826e0, ...)
2018-01-23T22:37:15.185+0100 [DEBUG] plugin.terraform-provider-proxmox: 	/home/travis/.gimme/versions/go/src/net/rpc/server.go:381 +0x134
2018-01-23T22:37:15.185+0100 [DEBUG] plugin.terraform-provider-proxmox: created by net/rpc.(*Server).ServeCodec
2018-01-23T22:37:15.185+0100 [DEBUG] plugin.terraform-provider-proxmox: 	/home/travis/.gimme/versions/go/src/net/rpc/server.go:475 +0x34e
2018/01/23 22:37:15 [ERROR] root: eval: *terraform.EvalConfigProvider, err: unexpected EOF
2018/01/23 22:37:15 [ERROR] root: eval: *terraform.EvalSequence, err: unexpected EOF
2018/01/23 22:37:15 [ERROR] root: eval: *terraform.EvalOpFilter, err: unexpected EOF
2018/01/23 22:37:15 [ERROR] root: eval: *terraform.EvalSequence, err: unexpected EOF
2018/01/23 22:37:15 [TRACE] [walkPlan] Exiting eval tree: provider.proxmox
2018-01-23T22:37:15.186+0100 [DEBUG] plugin: plugin process exited: path=/home/jjann/.terraform.d/plugins/terraform-provider-proxmox
2018/01/23 22:37:15 [TRACE] dag/walk: upstream errored, not walking "proxmox_resource_vm.test"
2018/01/23 22:37:15 [TRACE] dag/walk: upstream errored, not walking "provider.proxmox (close)"
2018/01/23 22:37:15 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2018/01/23 22:37:15 [TRACE] dag/walk: upstream errored, not walking "root"
2018/01/23 22:37:15 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-01-23T22:37:15.186+0100 [WARN ] plugin: error closing client during Kill: err="connection is shut down"



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
~~~~
Why do I get a `provider.proxmox: unexpected EOF`

What's wrong? Thanks in advance for your answer 

If you like I can help you with the missing documentation for Resource Configuration :)

Thanks for the great work 👍

**Comment by lord2800** [comment]
> panic: Post goofy/api2/json/access/ticket: unsupported protocol scheme ""

This seems to be the root of your problem.

**Comment by Nokius** [comment]
@lord2800 thanks I was looking at a different end. :bowing_man: 

this `main.tf`is doing what I like to do 
~~~~
provider "proxmox" {
  host = "https://goofy:8006"
}

resource "proxmox_resource_vm" "test" {
  vm_id = "105"
  node = "goofy"
  name = "test"
  memory = "512"
  cores = "1"
}
~~~~
